version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ps_db
      POSTGRES_USER: ps_user
      POSTGRES_PASSWORD: ps_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: backend_rds
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ps_db
      DB_USER: ps_user
      DB_PASSWORD: ps_password
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
