name: Backend RDS CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: vitaliio/backend_rds  # имя образа на Docker Hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version and commit hash
      id: vars
      run: |
        # Получаем версию из последнего тега
        TAG_VERSION=$(git describe --tags --abbrev=0 || echo "latest")
        # Получаем короткий хеш текущего коммита
        COMMIT_HASH=$(git rev-parse --short HEAD)
        # Устанавливаем тег версии с хешем коммита
        echo "version=$TAG_VERSION-$COMMIT_HASH" >> $GITHUB_ENV

    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ env.version }} -f Dockerfile .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:${{ env.version }}
