name: Backend RDS CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: vitaliio/backend_rds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from Git tag
      id: vars
      run: |
        TAG_VERSION=$(git describe --tags --abbrev=0 || echo "latest")
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
        echo "version=${TAG_VERSION}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:${TAG_VERSION}-${GITHUB_RUN_NUMBER} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:${TAG_VERSION}-${GITHUB_RUN_NUMBER}
